### ISSUE TITLE
Crash on background thread

### ISSUE THREAD

**Issue by cwc** [RuralRouteSoftware/ShareToIRC#1]
[This block](https://github.com/RuralRouteSoftware/ShareToIRC/blob/53074ff39f5ca1a4c83d56f2ce91bca05071d15c/share-to-irc/src/main/java/com/rrs_apps/android/share_to_irc/ShareTextService.java#L70-L72) needs to be on the UI thread. Calling `onError` instead would suffice.

Stacktrace:

```
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:200)
at android.os.Handler.<init>(Handler.java:114)
at android.widget.Toast$TN.<init>(Toast.java:384)
at android.widget.Toast.<init>(Toast.java:113)
at android.widget.Toast.makeText(Toast.java:272)
at android.widget.Toast.makeText(Toast.java:321)
at com.rrs_apps.android.share_to_irc.ShareTextService.sendTextToServer(ShareTextService.java:72)
at com.rrs_apps.android.share_to_irc.ShareTextService_.access$201(ShareTextService_.java:16)
at com.rrs_apps.android.share_to_irc.ShareTextService_$3.execute(ShareTextService_.java:66)
at org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:302)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
```

**Comment by cwc** [comment]
Fixed in e8e3ed35d1001b0f2c9f5b5f9b18f7d48e3527d9.
